name: deploy

on:
  workflow_dispatch:
    inputs:
      partyConfig:
        type: choice
        description: 'Party config'
        required: true
        options:
        - temple
        - tstvhq
      partyTheme:
        type: choice
        description: 'Party theme'
        required: true
        options:
        - temple
        - tst
      vhqPlaceholderEnabled:
        type: boolean
        description: 'VHQ placeholder enabled'
        default: true
      cognitoAllowedGroups:
        type: string
        description: 'Allowed Cognito groups'
        default: 'Caretakers PR Benefactors AllHolidays2022 Temple1January22'
      shutdownTime:
        description: 'Shutdown time'
        type: string
        required: true
        default: '00:00:15'

defaults:
  run:
    # explicitly setting `bash` enables safe settings (errexit, pipefail, ...)
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Print config"
      run: |
        echo "Config: ${{ github.event.inputs.partyConfig }}"
        echo "Theme: ${{ github.event.inputs.partyTheme }}"
        echo "VHQ Placeholder Enabled: ${{ github.event.inputs.vhqPlaceholderEnabled }}"
        echo "Cognito Allowed Groups: ${{ github.event.inputs.cognitoAllowedGroups }}"

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Open
      uses: ./.github/actions/tf-apply
      with:
        vhqEnabled: true
        partyConfig: ${{ github.event.inputs.partyConfig }}
        partyTheme: ${{ github.event.inputs.partyTheme }}
        vhqPlaceholderEnabled: ${{ github.event.inputs.vhqPlaceholderEnabled }}
        cognitoAllowedGroups: ${{ github.event.inputs.cognitoAllowedGroups }}

        #    - name: Delay
        #      uses: cardinalby/js-eval-action@v1
        #      env:
        #        targetTime: ${{ github.event.inputs.shutdownTime }}
        #        timezone: America/New_York
        #      with:
        #        expression: |
        #          {
        #            function changeTimezone(date, ianatz) {
        #              var invdate = new Date(date.toLocaleString('en-US', {
        #                timeZone: ianatz
        #              }));
        #
        #              var diff = date.getTime() - invdate.getTime();
        #
        #              return new Date(date.getTime() - diff); // needs to substract
        #            }
        #
        #            const now = new Date();
        #            const nowLocal = changeTimezone(now, env.timezone);
        #
        #            const targetTimeArray = /^(\d){2}:(\d){2}/.exec(env.targetTime);
        #            const targetHours = targetTimeArray[0];
        #            const targetMinutes = targetTimeArray[1];
        #
        #            if (nowLocal.getHours() - targetHours >= 0 &&
        #                nowLocal.getMinutes() - targetMinutes >= 0) {
        #              var targetTime = nowLocal;
        #
        #              if (nowLocal.getHours() - targetHours > 8) {
        #                targetTime = targetTime + new Date(0, 0, 1);
        #              }
        #
        #              targetTime.setHours(targetHours);
        #              targetTime.setMinutes(targetMinutes);
        #            }
        #
        #            while (nowLocal < targetTime) {
        #              await sleep(1000);
        #            }
        #
        #            return true;
        #          }
        #
        #    - name: Close
        #      uses: ./.github/actions/tf-apply
        #      with:
        #        vhqEnabled: false
        #        partyConfig: ${{ github.event.inputs.partyConfig }}
        #        partyTheme: ${{ github.event.inputs.partyTheme }}
        #        vhqPlaceholderEnabled: ${{ github.event.inputs.vhqPlaceholderEnabled }}
        #        cognitoAllowedGroups: ${{ github.event.inputs.cognitoAllowedGroups }}
        #


